// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuWUDZv19XhTnfRHOhj7lvNiDTJ5JF5JQ',
    appId: '1:572145211961:web:994601cd4e93ac468e4be8',
    messagingSenderId: '572145211961',
    projectId: 'travel-social-network-ad4b0',
    authDomain: 'travel-social-network-ad4b0.firebaseapp.com',
    storageBucket: 'travel-social-network-ad4b0.appspot.com',
    measurementId: 'G-D7Z369J7LN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuhg_2G1Kzjx7jI5eic3EV63hV0hQEX5w',
    appId: '1:572145211961:android:a1af626c2cf807ae8e4be8',
    messagingSenderId: '572145211961',
    projectId: 'travel-social-network-ad4b0',
    storageBucket: 'travel-social-network-ad4b0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBk5ibL1h-hEhmqltqgxHJSCL7oTb6FA2E',
    appId: '1:572145211961:ios:7a88f7e93ab68f6c8e4be8',
    messagingSenderId: '572145211961',
    projectId: 'travel-social-network-ad4b0',
    storageBucket: 'travel-social-network-ad4b0.appspot.com',
    iosClientId: '572145211961-26hto7t5e8ieq187idgistujsr59tdb8.apps.googleusercontent.com',
    iosBundleId: 'com.example.travelSocialNetwork',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBk5ibL1h-hEhmqltqgxHJSCL7oTb6FA2E',
    appId: '1:572145211961:ios:7a88f7e93ab68f6c8e4be8',
    messagingSenderId: '572145211961',
    projectId: 'travel-social-network-ad4b0',
    storageBucket: 'travel-social-network-ad4b0.appspot.com',
    iosClientId: '572145211961-26hto7t5e8ieq187idgistujsr59tdb8.apps.googleusercontent.com',
    iosBundleId: 'com.example.travelSocialNetwork',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDuWUDZv19XhTnfRHOhj7lvNiDTJ5JF5JQ',
    appId: '1:572145211961:web:7e28aec55d3da78b8e4be8',
    messagingSenderId: '572145211961',
    projectId: 'travel-social-network-ad4b0',
    authDomain: 'travel-social-network-ad4b0.firebaseapp.com',
    storageBucket: 'travel-social-network-ad4b0.appspot.com',
    measurementId: 'G-Z1TP74RGY4',
  );

}